#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossPassaRegua.Droid.Resource", IsApplication=true)]

namespace MvvmCrossPassaRegua.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int accent = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int divider = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int icons = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primary_dark = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primary_light = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int primary_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int secondary_text = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int lblPessoas = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int lblResultado = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int lblValorTotal = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int myButton = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int seekBarPessoas = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int txtValor = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
